######################################################################
# Author: Bernie Santos, Wyatt McQueen
# Username: Wyatt, Santosb2
#
# Assignment: P01: Wing Dash
#
# Purpose: Learn about classes, inheritance, and Pygame
######################################################################
# Acknowledgements: https://www.w3resource.com/python-exercises/tkinter/python-tkinter-canvas-and-graphics-exercise-10.php?utm_source=chatgpt.com,
#
# Inspired by Zelda, rebuilt into Python by: https://github.com/clear-code-projects/Zelda
# Art generated by Stable Diffusion: https://stablediffusionweb.com/app/image-generator
# Borrowed some ideas from: https://realpython.com/pygame-a-primer/

# Attribution-Noncommercial-Share Alike 3.0 United States License.
####################################################################################


from tkinter import *
import random
import time
window = Tk()
window.title("Wing Dash")
canvas = Canvas(window,width=400,height=600)
canvas.pack()
Bird_speed = 2
Pipe_colors = ["green"]


class Bird:
    def __init__(self,canvas,x,y):
        self.canvas = canvas
        self.x = x
        self.y = y
        self.gravity = 1.2
        self.fly = -20
        self.velocity = 0

        self.image = PhotoImage(file="Flappy-Bird-PNG-Pic.png")

        self.id = canvas.create_image(self.x,self.y,image=self.image,anchor=NW)

    def jump(self):
        self.velocity = self.fly


    def draw(self):
        pass


    def move(self):
        self.velocity += self.gravity
        self.y += self.velocity

        self.canvas.move(self.id,0,self.velocity)


class Pipe:
    def __init__(self,canvas,width,height):
        self.canvas = canvas
        self.width = width
        self.height = height

    def draw(self):
        pass

    def slide(self):
        pass

class Game:
    def __init__(self,canvas,width,height):
        self.canvas = canvas
        self.width = width
        self.height = height
        self.bird = Bird(canvas,50,250)

    def draw_background(self):
        self.canvas.create_rectangle(0,0,self.width,self.height,fill="skyblue",outline="")


    def spawn_pipe(self):
        pass

    def check_collision(self):
        pass

    def draw (self):
        self.draw_background()

        pass

    def restart(self):
        pass

    def run_game(self):
        self.bird.move()
        self.canvas.after(20,self.run_game)
        pass

game = Game(canvas,400,600)
game.draw()
window.bind("<space>",lambda e: game.bird.jump())
game.run_game()
window.mainloop()